[package]
name = "proto_api"
version = "1.0.0"
edition = "2021"

[dependencies]
tonic = { version = "0.9", features = ["tls"] }
prost = "0.11"
prost-types = "0.11"


[build-dependencies]
tonic-build = "0.8"
